peer-base/peer-base

README.md, src/app.js, src/collaboration/index.js, src/collaboration/shared.js, src/collaboration/store.js, src/keys/index.js, src/keys/uri-decode.js, src/keys/uri-encode-read-only.js
=> Adds support for read-only keys

README.md, src/collaboration/index.js, src/collaboration/shared.js
=> feat: state changed event says whether it's from self or not

src/app.js, src/collaboration/connection-manager.js, src/collaboration/index.js, src/collaboration/membership.js, src/common/eq-set.js, src/common/set-diff.js, src/transport/global-connection-manager.js
=> adds membership removal detection and propagation

README.md, package.json, src/collaboration/pull-protocol.js, src/collaboration/push-protocol.js, src/collaboration/shared.js, src/collaboration/store.js, src/common/eq-set.js, src/common/set-diff.js, src/common/vectorclock.js, test/collaboration-protocol.spec.js, test/performance/one-collaboration-many-peers.js, test/performance/replica.js
When syncing, join pending deltas to send them in batch.
When creating deltas, debounce the creation to create a join delta buffer.
=> Batch deltas

README.md, docs/PERFORMANCE-TESTS.md, package.json, src/collaboration/connection-manager.js, src/collaboration/index.js, src/collaboration/membership.js, test/performance/one-collaboration-many-peers.js, test/performance/one-seed-many-replicas.js, test/performance/replica.js
=> Fixes membership

README.md, bin/pinner, bin/pinner.js, examples/react-app/src/App.js, package.json, src/collaboration/index.js, src/collaboration/membership.js, src/collaboration/push-protocol.js, src/collaboration/shared.js, src/collaboration/store.js, src/pinner/index.js, src/transport/discovery.js
Pinner command. The Pinner does opaque replication for a peer-* app. The Pinner does not know about the collaboration keys, it just replicates the deltas blindly.
=> adds `pinner` implementation and command

src/common/ring.js, test/ring.spec.js
=> Add test and fix for .at() with a point before all points in ring

test/common/dias-set-inbound-conns.js
To run this test:
`npx aegir test -t node -f test/common/dias-set-inbound-conns.js`
=> Add test for dias set distribution

package.json, src/common/dias-peer-set.js, test/app-transport.spec.js, test/common/dias-set-inbound-conns.js, test/dias-set-inbound-conns.spec.js, test/dias-set.spec.js, test/unit-tests.js
Should fix DiasSet breakpoints and #99
=> fix: DiasSet break points

src/collaboration/membership.js
=> fix: deduplicates membeship addresses

README.md, bin/pinner, src/collaboration/index.js, src/collaboration/protocol.js, src/collaboration/pull-protocol.js, src/collaboration/push-protocol.js, src/collaboration/shared.js, src/collaboration/store.js, src/pinner/index.js, test/collaboration-gossip.spec.js
=> pinner should only get state

src/collaboration/membership-gossip-frequency-henristic.js
=> membership heuristic sampling function should be synchronous

package.json, src/collaboration/membership.js, src/common/dias-peer-set.js, test/membership.spec.js
Several fixes to membership, with accompanying tests.
Note: the tests will not all pass until https://github.com/ipfs-shipyard/js-delta-crdts/pull/23 is merged
Note also that I found another bug in ormap that I have [included a test for](https://github.com/ipfs-shipyard/peer-star-app/pull/112/files#diff-9697b8ec03600bdf064c345c915b586fR228) in membership.spec.js (the test is currently skipped). I need to move the test to js-delta-crdts and investigate the root cause.
=> Fix issues with membership

docs/API.md, package.json, src/app.js, src/collaboration/index.js, src/collaboration/membership.js, src/pinner/index.js, test/app-swarm.spec.js, test/app-transport.spec.js, test/app.spec.js, test/collaboration-gossip.spec.js, test/collaboration-protocol.spec.js, test/collaboration.spec.js, test/membership.spec.js, test/pinner.spec.js, test/public-collaboration.spec.js, test/replication.spec.js, test/shared.spec.js, test/stats.spec.js, test/sub-collaboration.spec.js, test/utils/create-app.js, test/utils/wait-for-members.js, test/utils/wait-for-value.js
=> WIP: speed-up tests

src/collaboration/clocks.js, src/collaboration/pull-protocol.js, src/collaboration/push-protocol.js, src/common/vectorclock.js
=> WIP: sends vector clock diffs instead of entire vector clock

.travis.yml, Procfile, package.json
Closes https://github.com/protocol/infra/issues/398
This is not tested but pretty boilerplate stuff & a deploy works locally with this config
=> Configure Heroku deployment on merges to master

sim/javascripts/network.js
Fixes https://github.com/ipfs-shipyard/peer-star-app/issues/174
=> fix: update sim to match Membership constructor

.travis.yml, README.md
Began adding the discussify pinner as well, but as config values haven't
been received from the team yet, it's commented out
License: MIT
Signed-off-by: Victor Bjelkholm <git@victor.earth>
=> Add post-deploy test for pinners

src/common/vectorclock.js, test/vectorclock.spec.js
Adds test for https://github.com/peer-base/peer-base/pull/210
=> add missing vector clock test

test/collaboration/membership-gossip-frequency-heuristic.spec.js
I'm assuming this fix is what was intended.
=> Fix lint error

examples/react-app/src/CreateKey.js
Removing shouldComponentUpdate makes it work.
=> Fix redirect after key generation
