README.md, examples/react-app/src/App.js, examples/react-app/src/lib/discussion-tree-crdt.js, src/collaboration/clocks.js, src/collaboration/index.js, src/collaboration/protocol.js, src/collaboration/pull-protocol.js, src/collaboration/push-protocol.js, src/collaboration/store.js, src/transport/global-connection-manager.js, test/collaboration-protocol.spec.js, test/shared.spec.js
* Delta retention maximum (defaults to 1000)
* Prevents sending data back to the sender, which, besides being wasteful, was forcing the connection to go to lazy mode. The solution is to centralise clocks for all the peers in an entire collaboration.
* Docs: Fixes documentation of options..
=> feature: delta retention

package.json
Version 0.32.3 of js-ipfs has regressions:
https://travis-ci.org/ipfs-shipyard/peer-star-app/builds/435707042
Forcing 0.32.2 will get the tests passing again:
https://travis-ci.org/jimpick/peer-star-app/builds/437465067
We should investigate the regressions, of course, but I will be submitting some other pull requests, and it would be nice for them to pass on Travis.
=> Force js-ipfs 0.32.2

src/collaboration/connection-manager.js
Right now, it's using inbound connections to set outbound peers.
=> Set outbound peers in observer from outbound connections

src/common/ring.js
Because the `i` variable from the for..in loop is a string, the `i + 1` code would be too large and would end up removing most of the points.
=> Fix ring .remove() bug due to string/integer types

src/transport/global-connection-manager.js
The map isn't indexed with peerInfo
=> Use peerId with _peerCollaborations.get() in Global Connection Manager

src/common/dias-peer-set.js, test/dias-set.spec.js
If a ring is small, it may not have a very even distribution of points.
This change modifies the Dias Set so it will grab the next unused successor in the ring, going all the way around the ring, at most once, if necessary. So for small rings of 6 or less points, all the points will be added to the Dias Set.
=> Fix small dias sets

src/collaboration/store.js
I think perhaps the name convention for the keys changed?
This fix only looks at the last 3 hex characters of the key ...
that might not be correct.
=> Fix delta trimming

bin/pinner
This commit makes the pinner cli a bit more usable for infra-folks to be able to deploy peer-star-app easily.
cc @jimpick 
License: MIT
Signed-off-by: Victor Bjelkholm <git@victor.earth>
=> fix: pinner to use env vars for config + default values

README.md, package.json, test/deployed-pinner-test.js
This commit adds a test that allows us to test a pinner after it's been
deployed, handy to make sure the deployment is working correctly and
could additionally be used as status checks.
More information in the test file itself.
Solves https://github.com/ipfs-shipyard/peer-star-app/issues/155
License: MIT
Signed-off-by: Victor Bjelkholm <git@victor.earth>
=> feature: post-deploy tests for pinner

bin/pinner, package.json, src/collaboration/protocol.js, src/pinner/index.js, src/pinner/pinner-metrics.js, src/transport/global-connection-manager.js
=> Feature: expose pinner metrics

src/pinner/index.js
Should fix #177 as a side effect.
=> fix: pinner: correcly accounts for collaboration timeout for removal

src/pinner/pinner-metrics.js
Instead of inc/dec a counter, we grab the values and set them once every
REFRESH_INTERVAL ms, defaults to 5000.
License: MIT
Signed-off-by: Victor Bjelkholm <git@victor.earth>
=> fix: set metrics every 5 seconds

docs/API.md, src/collaboration/push-protocol.js, src/collaboration/replication.js, test/replication.spec.js
Adds:
* `collaboration.replication.pinnerPeers()`
* `collaboration.replication.isCurrentStatePersistedOnPinner()`
* `collaboration.replication.emit('pinner joined', peerId)`
* `collaboration.replication.emit('pinner left', peerId)`
=> Feature: replication pin status: new queries and events

package.json, src/collaboration/clocks.js, src/collaboration/index.js, src/collaboration/pull-protocol.js, src/collaboration/push-protocol.js, src/collaboration/shared.js
Pinner was saving states with vector clocks, but since states may diverge between replicas and as the pinner is not able to merge states, the vector clocks cannot be merged.
This makes the state coherent with the vector clock on the pinner.
=> Fix: pinner: makes the state coherent with the vector clock

src/collaboration/shared.js
Handle case where state is already loaded before apply is called.
Needed to fix editing issues after page reload in PeerPad. https://github.com/ipfs-shipyard/peer-pad/issues/273
(sorry, no test)
=> Initialize incremental value cache if it hasn't been initialized yet

src/common/vectorclock.js
This was causing deltas to be applied when the underlying state
didn't exist yet...
This was causing corruption in PeerPad. I was able to debug this
thanks to the runtime checks from this patch:
https://github.com/ipfs-shipyard/js-delta-crdts/pull/34
=> Fix missing spread operator in isDeltaInteresting

src/collaboration/clocks.js, src/collaboration/index.js, src/collaboration/peer-to-clock-id.js, src/collaboration/pull-protocol.js, src/collaboration/push-protocol.js, src/collaboration/shared.js, src/common/vectorclock.js, test/collaboration-random.spec.js, test/pinner.spec.js, test/vectorclock.spec.js
Fixes:
- When pull protocol received a clock, it would set a timer to wait for the corresponding data for the clock. But each time it received a new clock it would keep extending that timer. Now it sets a different timer per clock, and clears that timer only when data is received with a new clock that subsumes the one we were waiting for.
- It now cancels timers when the pull protocol is ended
- Pull protocol would switch to lazy mode whenever it received state, even if the state wasn't actually saved. This change makes it more judicious
- Push protocol now waits until it receives a message indicating whether the remote peer is a pinner before sending data. This helps avoid the scenario where we send deltas to a pinner instead of the full state (the pinner doesn't understand deltas …
=> Several fixes for push / pull protocols

src/collaboration/push-protocol.js, test/collaboration/membership-gossip-frequency-heuristic.spec.js
When the remote puller tells a pusher to start pushing, the pusher should assume the given remote clock is the required clock, and thus should overwrite it instead of merging it.
This should account for the case when:
1)  the pusher was pushing changes that were being ignored by the puller
2) then it receives a "stop pushing" message,
3) then it receives a "start pushing" message.
In this case, pusher has fast-forwarded the clock while in state 1, and should reset when in 3.
=> fix: when push protocol resumes pushing, reset the remote clock

package.json
Newer versions of aegir cause `npm test` to fail because stream-to-pull-stream
1.7.2 has two 'destroy' methods (fixed in 1.7.3). We're stuck on 1.7.2
until js-ipfs is updated.
=> Lock aegir version

src/collaboration/shared.js
When loading an ORMap, it wasn't setting the CausalContext properly
when only being deserialized.
=> Join state after load with initial state

docs/API.md, docs/CODE-STRUCTURE.md, docs/PROTOCOL.md, examples/react-app/README.md, examples/react-app/package.json, examples/react-app/src/App.js, examples/react-app/src/CreateKey.js, examples/react-app/src/DiscussionTreeCollaboration.js
This minor fix will resolve the compilation error : 
Failed to compile.
./node_modules/peer-star-react/src/withCollaboration.js
Module not found: Can't resolve 'peer-star-app' in '/home/peer-base/examples/react- 
app/node_modules/peer-star-react/src'
=> minor fixes: swap peer-star-app to peer-base
